Lessons3_ClassesObjectsAndMethods
veronikagor/StLab_HomeWork pull request #4
Opened 2021-02-24 06:50 UTC by veronikagor

2021-02-24 10:45 UTC, mashadolya requested changes
1. Исправить все замечания 
2. Изучить code convention и испольовать в коде
3. Все интерфейсы храним в папке Interfaces
4. Для репортгенераторов тоже стоит создать отдельную директорию

2021-02-24 10:45 UTC, mashadolya commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/Models/BaseUser.cs
> +        public int JobSalary { get; set; }
почему бы не создать отдельный объект Job и хранить в нем эту инфу?

2021-02-24 10:45 UTC, mashadolya commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/Models/Employee.cs
> +        public string CompanyStreet { get; set; }
почему бы не создать отдельный объект Company и хранить в нем эту инфу?

2021-02-24 10:45 UTC, mashadolya commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/Factories/UserFactory.cs
> +        private Faker<TUser> GetBaseUserInfo<TUser>() where TUser : BaseUser
Для проектирование обобщенных типов используем обобщенный нейминг, т.е. не `TUser`, а просто `Т`

2021-02-24 10:45 UTC, mashadolya commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/Factories/UserFactory.cs
> +                .RuleFor(c => c.Id, f => Guid.NewGuid())
почему `с`?

2021-02-24 10:45 UTC, mashadolya commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/IReportGenerator.cs
> +        public int Compare(object a, object b);
Не понятно почему в интерфейсе для репортов метод, который сравнивает объекты

2021-02-24 10:45 UTC, mashadolya commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/EmployeeReportGenerator.cs
> +        public int Compare(object a, object b)
https://metanit.com/sharp/tutorial/3.23.php

2021-02-24 10:45 UTC, mashadolya commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/СandidateReportGenerator.cs
> +        public static void ShowSortedUserInfo(List<Candidate> candidates)
логчнее было бы вынести в инстерфейс `IReportGenerator ` этот метод, а не `Compare`

2021-02-24 10:45 UTC, mashadolya commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/Program.cs
> +            }
дублирование логики 
Посмотри в лекции пример с `IMovable`, вроде :)

2021-02-24 10:45 UTC, mashadolya commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/Program.cs
> +            var candidates = factory.GetCandidates(new Faker().Random.Int(1, 10));
Магические числа - антипаттерн, не используем их в коде

2021-02-24 11:33 UTC, veronikagor commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/Program.cs
> +            var candidates = factory.GetCandidates(new Faker().Random.Int(1, 10));
значит я могу оставить Random.Int() без аргументов?

2021-02-25 09:23 UTC, veronikagor commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/Models/BaseUser.cs
> +        public int JobSalary { get; set; }
сделано

2021-02-25 09:24 UTC, veronikagor commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/Models/Employee.cs
> +        public string CompanyStreet { get; set; }
создала класс и перенесла в него переменные

2021-02-25 09:25 UTC, veronikagor commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/Factories/UserFactory.cs
> +        private Faker<TUser> GetBaseUserInfo<TUser>() where TUser : BaseUser
сделано

2021-02-25 09:25 UTC, veronikagor commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/Factories/UserFactory.cs
> +                .RuleFor(c => c.Id, f => Guid.NewGuid())
переименовала в соответствии с типом использующихся объектов

2021-02-25 09:34 UTC, veronikagor commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/IReportGenerator.cs
> +        public int Compare(object a, object b);
метод для сравнения Compare реализовала  в отдельных классах для каждого вида юзеров

2021-02-25 09:35 UTC, veronikagor commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/EmployeeReportGenerator.cs
> +        public int Compare(object a, object b)
теперь метод Compare сравнивает юзеров одного типа

2021-02-25 09:36 UTC, veronikagor commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/СandidateReportGenerator.cs
> +        public static void ShowSortedUserInfo(List<Candidate> candidates)
вынесла в интерфейс два метода: для сортировки и для вывода информации

2021-02-25 09:38 UTC, veronikagor commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/Program.cs
> +            }
сделано

2021-02-25 09:40 UTC, veronikagor commented on Lessons3_ClassesObjectsMethods/Lessons3_ClassesObjectsMethods/Program.cs
> +            var candidates = factory.GetCandidates(new Faker().Random.Int(1, 10));
вынесла в константы

2021-02-26 13:17 UTC, mashadolya approved these changes

2021-02-26 13:17 UTC, merged