Lessons5_ExceptionHandling
veronikagor/StLab_HomeWork pull request #7
Opened 2021-03-15 08:42 UTC by veronikagor

2021-03-15 08:59 UTC, mashadolya requested changes

2021-03-15 08:59 UTC, mashadolya commented on Lessons5_ExceptionHandling/PhoneShop/Actions/Order.cs
> +                        log.Info($"Please, try again.");
а где сообщение об ошибке?

2021-03-15 08:59 UTC, mashadolya commented on Lessons5_ExceptionHandling/PhoneShop/Models/Phone.cs
> +    public class Phone : PhoneShops
зачем?

2021-03-15 08:59 UTC, mashadolya commented on Lessons5_ExceptionHandling/PhoneShop/Models/PhoneShops.cs
> +        public IList<Shop> Shops { get; set; }
почему IList?

2021-03-15 08:59 UTC, mashadolya commented on Lessons5_ExceptionHandling/PhoneShop/Program.cs
> +            var phoneShops = FileReading.ReadTheFile(fileName);
Лучше назвать `FileReader `или `JsonReader`

2021-03-15 08:59 UTC, mashadolya commented on Lessons5_ExceptionHandling/PhoneShop/Models/Phone.cs
> +        public string OperationSystemType { get; set; }
мы можем использовать наш енам тута

2021-03-15 08:59 UTC, mashadolya commented on Lessons5_ExceptionHandling/PhoneShop/Actions/Order.cs
> +        private static Phone FindDesiredShop(Dictionary<Shop, Phone> listOfShopsWithDesiredPhoneModel,
метод назввается `FindDesiredShop`, что подразумевает, что он просто нацден необходимый магазин
Почему он еще возвращает телефон заданный?
принцип единой ответственности...

2021-03-15 08:59 UTC, mashadolya commented on Lessons5_ExceptionHandling/PhoneShop/Actions/Order.cs
> +                    log.Info($"Shop '{desiredShopName}' is absent in the list. Please try again: ");
это скорее `log.error`
почитай про уровни логирования, когда какой используется и тд

2021-03-15 08:59 UTC, mashadolya commented on Lessons5_ExceptionHandling/PhoneShop/Actions/Order.cs
> +                    log.Debug($"Shop '{desiredShopName}' is absent in the list.\n{ex.StackTrace}");
Мы не выводим стек трейс в логи

2021-03-15 08:59 UTC, mashadolya commented on Lessons5_ExceptionHandling/PhoneShop/Actions/Order.cs
> +        public static Dictionary<Shop, Phone> FindShopsWithDesiredPhoneModel(PhoneShops phoneShops)
очень большой и непонятный метод
стоит раделить логику

2021-03-15 08:59 UTC, mashadolya commented on Lessons5_ExceptionHandling/PhoneShop/Actions/Order.cs
> +        public static Dictionary<Shop, Phone> FindShopsWithDesiredPhoneModel(PhoneShops phoneShops)
ну и есть ли смысл вообще в Dictionary тут

2021-03-15 08:59 UTC, mashadolya commented on Lessons5_ExceptionHandling/PhoneShop/Actions/CalculationThePhoneCount.cs
> +    public class CalculationThePhoneCount
Странный класс
я бы просто сделала PhoneShopHelper и в нем поместила все методы для работы с магазином

2021-03-19 09:07 UTC, Maria-Dolia requested changes

2021-03-19 09:07 UTC, Maria-Dolia commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +                    $"The count of phones with IOS in {shop.Name} is {countIosIsAvailableInShop}");
можно сделать так, чтобы не дублировать это сообщение для ios и android телефонов

2021-03-19 09:07 UTC, Maria-Dolia commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +                        if (phone.IsAvailable)
а в одном ифе не можем проеврять?

2021-03-19 09:07 UTC, Maria-Dolia commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +        private static bool _isPhoneModelAvailable;
не совсем понятно почему эти переменные глобальные

2021-03-19 09:07 UTC, Maria-Dolia commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +                if (shop.Name.ToUpper().Equals(_desiredShopName.ToUpper()))
на каждой итерации цикла делаем `toUpper` для `_desiredShopName`

2021-03-19 09:07 UTC, Maria-Dolia commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +                foreach (var phone in shop.Phones.Where(phone => phone.Model.Equals(_desiredPhoneModel)))
что если `_desiredPhoneModel `null? 
Поэтому лучше было сделать эту переменную локальной

2021-03-19 09:07 UTC, Maria-Dolia commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +            bool isPhoneModelAvailable = false;
const?

2021-03-19 09:07 UTC, Maria-Dolia commented on Lessons5_ExceptionHandling/PhoneShop/Exceptions/ShopNotFoundException.cs
> +        public ShopNotFoundException(string? message) : base(message)
почему налбл?

2021-03-19 09:07 UTC, Maria-Dolia commented on Lessons5_ExceptionHandling/PhoneShop/Models/Phone.cs
> +
лишняя пустая строка

2021-03-19 09:07 UTC, Maria-Dolia commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +            )
что за скобочка?

2021-03-19 09:07 UTC, Maria-Dolia commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +            foreach (var shop in _shopList.Where(shop => shop.Name.ToUpper().Equals(_desiredShopName.ToUpper()))
Опять аппер на каждой итерации делаем?

2021-03-19 09:07 UTC, Maria-Dolia commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +        public PhoneShopHelper(PhoneShops phoneShop)
я бы все таки делала класс статическим

2021-03-19 09:07 UTC, Maria-Dolia commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +        }
этот метод надо перерарботать чтобы избавиться от дублирования лог инфо

2021-03-19 10:52 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +            bool isPhoneModelAvailable = false;
isPhoneModelExist, isPhoneModelAvailable меняются во время прохождения цикла.

2021-03-20 07:55 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Actions/Order.cs
> +                        log.Info($"Please, try again.");
добавила:)

2021-03-20 07:56 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Program.cs
> +            var phoneShops = FileReading.ReadTheFile(fileName);
переименовала

2021-03-20 07:56 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Models/Phone.cs
> +        public string OperationSystemType { get; set; }
сделано)

2021-03-20 07:57 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Actions/Order.cs
> +        private static Phone FindDesiredShop(Dictionary<Shop, Phone> listOfShopsWithDesiredPhoneModel,
изменила

2021-03-20 07:57 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Actions/Order.cs
> +                    log.Info($"Shop '{desiredShopName}' is absent in the list. Please try again: ");
сделано

2021-03-20 07:58 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Actions/Order.cs
> +                    log.Debug($"Shop '{desiredShopName}' is absent in the list.\n{ex.StackTrace}");
ок. переделала

2021-03-20 07:58 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Actions/Order.cs
> +        public static Dictionary<Shop, Phone> FindShopsWithDesiredPhoneModel(PhoneShops phoneShops)
разделила и переписала с List

2021-03-20 07:58 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Actions/CalculationThePhoneCount.cs
> +    public class CalculationThePhoneCount
сделано

2021-03-20 07:58 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +                    $"The count of phones with IOS in {shop.Name} is {countIosIsAvailableInShop}");
сделано

2021-03-20 09:18 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +                        if (phone.IsAvailable)
в каждом цикле if заполняются свои булевы переменные для проверки в ChekThatPhoneAvailableToOrder.

2021-03-20 09:19 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +        private static bool _isPhoneModelAvailable;
сделала локальными.

2021-03-20 09:20 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +                if (shop.Name.ToUpper().Equals(_desiredShopName.ToUpper()))
использовала  (StringComparison.OrdinalIgnoreCase) для решения проблемы

2021-03-20 09:20 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +                foreach (var phone in shop.Phones.Where(phone => phone.Model.Equals(_desiredPhoneModel)))
сделала локальной

2021-03-20 09:21 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Exceptions/ShopNotFoundException.cs
> +        public ShopNotFoundException(string? message) : base(message)
налбл не нужен:)

2021-03-20 09:21 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Models/Phone.cs
> +
удалила

2021-03-20 09:22 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +            )
идея переносит по причине длинной строки, не заметила:)

2021-03-20 09:22 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +            foreach (var shop in _shopList.Where(shop => shop.Name.ToUpper().Equals(_desiredShopName.ToUpper()))
иправила

2021-03-20 09:23 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +        public PhoneShopHelper(PhoneShops phoneShop)
сделала статическим.

2021-03-20 09:23 UTC, veronikagor commented on Lessons5_ExceptionHandling/PhoneShop/Actions/PhoneShopHelper.cs
> +        }
переработала.

2021-03-22 08:28 UTC, Maria-Dolia approved these changes

2021-03-22 12:44 UTC, merged